# Generated by Django 5.2.3 on 2025-06-15 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforms', '0001_initial'),
    ]

    operations = [
    ]
