# Generated by Django 5.2.3 on 2025-06-15 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workforms', '0002_auto_20250615_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=40)),
                ('site_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('door_Code', models.CharField(max_length=20)),
                ('installation_type', models.CharField(choices=[('Swing Door', 'Swing Door'), ('Slide Door', 'SLide Door'), ('Fold Door', 'Fold Door')], max_length=50)),
                ('controller_type', models.CharField(max_length=30)),
                ('controller_condition', models.CharField(choices=[('Good', 'Good'), ('Requires Replacement', 'Requires Replacement'), ('Requires Attention', 'Requires Attention'), ('Replaced', 'Replaced'), ('Repaired', 'Repaired'), ('N/A', 'N/A)')], max_length=50)),
                ('selector_type', models.CharField(choices=[('BDE-D', 'BDE-D'), ('BDE-K', 'BDE-K'), ('BDE-M', 'BDE-M'), ('Other', 'Other')], max_length=50)),
                ('selector_other', models.CharField(blank=True, max_length=50)),
                ('door_type', models.CharField(choices=[('Aluminum', 'Aluminum'), ('Wood', 'Wood'), ('Glass Door', 'Glass Door')], max_length=50)),
                ('door_condition', models.CharField(choices=[('Good', 'Good'), ('Requires Replacement', 'Requires Replacement'), ('Requires Attention', 'Requires Attention'), ('Replaced', 'Replaced'), ('Repaired', 'Repaired'), ('N/A', 'N/A)')], max_length=50)),
                ('arm_type', models.CharField(blank=True, choices=[('Push Arm', 'Push Arm'), ('Slide Arm', 'Slide Arm'), ('Articulated Arm', 'Articulated Arm')], max_length=50)),
                ('arm_condition', models.CharField(blank=True, choices=[('Good', 'Good'), ('Requires Replacement', 'Requires Replacement'), ('Requires Attention', 'Requires Attention'), ('Replaced', 'Replaced'), ('Repaired', 'Repaired'), ('N/A', 'N/A)')], max_length=50)),
                ('roller_condition', models.CharField(blank=True, choices=[('Good', 'Good'), ('Requires Replacement', 'Requires Replacement'), ('Requires Attention', 'Requires Attention'), ('Replaced', 'Replaced'), ('Repaired', 'Repaired'), ('N/A', 'N/A)')], max_length=50)),
                ('battery_condition', models.CharField(blank=True, choices=[('Good', 'Good'), ('Requires Replacement', 'Requires Replacement'), ('Requires Attention', 'Requires Attention'), ('Replaced', 'Replaced'), ('Repaired', 'Repaired'), ('N/A', 'N/A)')], max_length=50)),
                ('internal_activation', models.CharField(choices=[('RIC290', 'RIC290'), ('RAD290', 'RAD290'), ('AIS290', 'AIS290'), ('HR100', 'HR100'), ('HR94', 'HR94'), ('HR54', 'HR54'), ('Domino', 'Domino'), ('BER Activation', 'BER Activation'), ('Record Swing', 'Record Swing'), ('Hotron Swing', 'Hotron Swing'), ('WF Button', 'WF Button'), ('Button', 'Button'), ('Swipe Card', 'Swipe Card'), ('Eye Beams', 'Eye Beams'), ('N/A', 'N/A')], max_length=50)),
                ('internal_activation_condition', models.CharField(choices=[('Good', 'Good'), ('Requires Replacement', 'Requires Replacement'), ('Requires Attention', 'Requires Attention'), ('Replaced', 'Replaced'), ('Repaired', 'Repaired'), ('N/A', 'N/A)')], max_length=50)),
                ('external_activation', models.CharField(choices=[('RIC290', 'RIC290'), ('RAD290', 'RAD290'), ('AIS290', 'AIS290'), ('HR100', 'HR100'), ('HR94', 'HR94'), ('HR54', 'HR54'), ('Domino', 'Domino'), ('BER Activation', 'BER Activation'), ('Record Swing', 'Record Swing'), ('Hotron Swing', 'Hotron Swing'), ('WF Button', 'WF Button'), ('Button', 'Button'), ('Swipe Card', 'Swipe Card'), ('Eye Beams', 'Eye Beams'), ('N/A', 'N/A')], max_length=50)),
                ('external_activation_condition', models.CharField(choices=[('Good', 'Good'), ('Requires Replacement', 'Requires Replacement'), ('Requires Attention', 'Requires Attention'), ('Replaced', 'Replaced'), ('Repaired', 'Repaired'), ('N/A', 'N/A)')], max_length=50)),
                ('safety_sensor', models.CharField(choices=[('RIC290', 'RIC290'), ('RAD290', 'RAD290'), ('AIS290', 'AIS290'), ('HR100', 'HR100'), ('HR94', 'HR94'), ('HR54', 'HR54'), ('Domino', 'Domino'), ('BER Activation', 'BER Activation'), ('Record Swing', 'Record Swing'), ('Hotron Swing', 'Hotron Swing'), ('WF Button', 'WF Button'), ('Button', 'Button'), ('Swipe Card', 'Swipe Card'), ('Eye Beams', 'Eye Beams'), ('N/A', 'N/A')], max_length=50)),
                ('safety_sensor_condition', models.CharField(choices=[('Good', 'Good'), ('Requires Replacement', 'Requires Replacement'), ('Requires Attention', 'Requires Attention'), ('Replaced', 'Replaced'), ('Repaired', 'Repaired'), ('N/A', 'N/A)')], max_length=50)),
                ('open_speed', models.IntegerField()),
                ('close_speed', models.IntegerField()),
                ('hold_open', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('cycles', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(blank=True, upload_to='')),
                ('image3', models.ImageField(blank=True, upload_to='')),
                ('image4', models.ImageField(blank=True, upload_to='')),
                ('image5', models.ImageField(blank=True, upload_to='')),
                ('image6', models.ImageField(blank=True, upload_to='')),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Pending Approval', 'Pending Approval'), ('Invoiced', 'Invoiced'), ('Emailed', 'Emailed'), ('Complete', 'Complete')], default='Created', max_length=50)),
                ('site_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforms.site')),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_out_charge', models.FloatField(blank=True)),
                ('per_hour_charge', models.FloatField(blank=True)),
                ('service_charge', models.FloatField(blank=True)),
                ('site_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforms.site')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=60)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.IntegerField()),
                ('site_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforms.site')),
            ],
        ),
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True)),
                ('travel_time', models.FloatField(blank=True)),
                ('job_type', models.CharField(choices=[('Door Callout', 'Door Callout'), ('Door Service', 'Door Service'), ('Door Installation', 'Door Installation'), ('Gate Callout', 'Gate Callout'), ('Gate Service', 'Gate Service'), ('Gate Installation', 'Gate Installation'), ('Electrical Callout', 'Electrical Callout'), ('Electrical Service', 'Electrical Service'), ('Electrical Installation', 'Electrical Installation'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('materials', models.TextField(blank=True)),
                ('num_electrcians', models.IntegerField()),
                ('num_apprentices', models.IntegerField()),
                ('electricians_name', models.CharField(max_length=30)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_signature', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Pending Approval', 'Pending Approval'), ('Invoiced', 'Invoiced'), ('Emailed', 'Emailed'), ('Complete', 'Complete')], default='Created', max_length=50)),
                ('signature', models.ImageField(blank=True, upload_to='')),
                ('image2', models.ImageField(blank=True, upload_to='')),
                ('image3', models.ImageField(blank=True, upload_to='')),
                ('image4', models.ImageField(blank=True, upload_to='')),
                ('image5', models.ImageField(blank=True, upload_to='')),
                ('image6', models.ImageField(blank=True, upload_to='')),
                ('site_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforms.site')),
            ],
        ),
    ]
