# Generated by Django 5.2.3 on 2025-06-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforms', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='site_address',
        ),
        migrations.AddField(
            model_name='site',
            name='address',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='site',
            name='aircode',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='site',
            name='country',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='site',
            name='county',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='site',
            name='town',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
