# Generated by Django 5.2.3 on 2025-06-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforms', '0004_remove_site_site_address_site_address_site_aircode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('item', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(choices=[('Van', 'Van'), ('Stores', 'Stores')], max_length=50)),
            ],
        ),
    ]
