# Generated by Django 5.2.3 on 2025-06-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforms', '0005_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='cost_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='sales_price',
            field=models.IntegerField(default=0),
        ),
    ]
