# Generated by Django 5.2.3 on 2025-06-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforms', '0007_rename_sales_price_stock_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='installation_type',
            field=models.CharField(choices=[('Swing Door', 'Swing Door'), ('Slide Door', 'Slide Door'), ('Fold Door', 'Fold Door')], max_length=50),
        ),
    ]
