# Generated by Django 5.2.3 on 2025-06-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforms', '0008_alter_service_installation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='arm_condition',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Requires Replacement', 'Requires Replacement'), ('Requires Attention', 'Requires Attention'), ('Replaced', 'Replaced'), ('Repaired', 'Repaired'), ('N/A', 'N/A')], max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='battery_condition',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Requires Replacement', 'Requires Replacement'), ('Requires Attention', 'Requires Attention'), ('Replaced', 'Replaced'), ('Repaired', 'Repaired'), ('N/A', 'N/A')], max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='controller_condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Requires Replacement', 'Requires Replacement'), ('Requires Attention', 'Requires Attention'), ('Replaced', 'Replaced'), ('Repaired', 'Repaired'), ('N/A', 'N/A')], max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='door_condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Requires Replacement', 'Requires Replacement'), ('Requires Attention', 'Requires Attention'), ('Replaced', 'Replaced'), ('Repaired', 'Repaired'), ('N/A', 'N/A')], max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='external_activation_condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Requires Replacement', 'Requires Replacement'), ('Requires Attention', 'Requires Attention'), ('Replaced', 'Replaced'), ('Repaired', 'Repaired'), ('N/A', 'N/A')], max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='internal_activation_condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Requires Replacement', 'Requires Replacement'), ('Requires Attention', 'Requires Attention'), ('Replaced', 'Replaced'), ('Repaired', 'Repaired'), ('N/A', 'N/A')], max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='roller_condition',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Requires Replacement', 'Requires Replacement'), ('Requires Attention', 'Requires Attention'), ('Replaced', 'Replaced'), ('Repaired', 'Repaired'), ('N/A', 'N/A')], max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='safety_sensor_condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Requires Replacement', 'Requires Replacement'), ('Requires Attention', 'Requires Attention'), ('Replaced', 'Replaced'), ('Repaired', 'Repaired'), ('N/A', 'N/A')], max_length=50),
        ),
    ]
