# Generated by Django 5.2.3 on 2025-06-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforms', '0009_alter_service_arm_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
