# Generated by Django 5.2.3 on 2025-06-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforms', '0010_alter_service_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
