# Generated by Django 5.2.3 on 2025-06-25 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforms', '0011_alter_service_date_alter_worksheet_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksheet',
            name='customer_signature',
        ),
    ]
